/**
 * Generated by orval v7.10.0 🍺
 * Do not edit manually.
 * Meetball API
 * API for Meetball - The Summeet's event networking platform
 * OpenAPI spec version: 0.1.0
 */
import type { AnswerReadIsAnonymous } from './answerReadIsAnonymous';
import type { AnswerReadIsHidden } from './answerReadIsHidden';
import type { AnswerReadIsDeleted } from './answerReadIsDeleted';
import type { AnswerReadIsFlagged } from './answerReadIsFlagged';
import type { AnswerReadIsSelected } from './answerReadIsSelected';
import type { AnswerReadIsOfficial } from './answerReadIsOfficial';
import type { AnswerReadIsOriginalPoster } from './answerReadIsOriginalPoster';
import type { AnswerReadCreatedAt } from './answerReadCreatedAt';
import type { AnswerReadUpdatedAt } from './answerReadUpdatedAt';

export interface AnswerRead {
  id: string;
  question_id: string;
  user_id: string;
  content: string;
  is_anonymous: AnswerReadIsAnonymous;
  is_hidden: AnswerReadIsHidden;
  is_deleted: AnswerReadIsDeleted;
  is_flagged: AnswerReadIsFlagged;
  is_selected: AnswerReadIsSelected;
  is_official: AnswerReadIsOfficial;
  is_original_poster: AnswerReadIsOriginalPoster;
  created_at: AnswerReadCreatedAt;
  updated_at: AnswerReadUpdatedAt;
}
