/**
 * Generated by orval v7.10.0 🍺
 * Do not edit manually.
 * Meetball API
 * API for Meetball - The Summeet's event networking platform
 * OpenAPI spec version: 0.1.0
 */
import type { AnswerCreateIsAnonymous } from './answerCreateIsAnonymous';
import type { AnswerCreateIsHidden } from './answerCreateIsHidden';
import type { AnswerCreateIsDeleted } from './answerCreateIsDeleted';
import type { AnswerCreateIsFlagged } from './answerCreateIsFlagged';
import type { AnswerCreateIsSelected } from './answerCreateIsSelected';
import type { AnswerCreateIsOfficial } from './answerCreateIsOfficial';
import type { AnswerCreateIsOriginalPoster } from './answerCreateIsOriginalPoster';

export interface AnswerCreate {
  question_id: string;
  user_id: string;
  content: string;
  is_anonymous: AnswerCreateIsAnonymous;
  is_hidden: AnswerCreateIsHidden;
  is_deleted: AnswerCreateIsDeleted;
  is_flagged: AnswerCreateIsFlagged;
  is_selected: AnswerCreateIsSelected;
  is_official: AnswerCreateIsOfficial;
  is_original_poster: AnswerCreateIsOriginalPoster;
}
