/**
 * Generated by orval v7.10.0 🍺
 * Do not edit manually.
 * Meetball API
 * API for Meetball - The Summeet's event networking platform
 * OpenAPI spec version: 0.1.0
 */
import type { AnswerUpdateIsAnonymous } from './answerUpdateIsAnonymous';
import type { AnswerUpdateIsHidden } from './answerUpdateIsHidden';
import type { AnswerUpdateIsDeleted } from './answerUpdateIsDeleted';
import type { AnswerUpdateIsFlagged } from './answerUpdateIsFlagged';
import type { AnswerUpdateIsSelected } from './answerUpdateIsSelected';
import type { AnswerUpdateIsOfficial } from './answerUpdateIsOfficial';
import type { AnswerUpdateIsOriginalPoster } from './answerUpdateIsOriginalPoster';

export interface AnswerUpdate {
  content: string;
  is_anonymous: AnswerUpdateIsAnonymous;
  is_hidden: AnswerUpdateIsHidden;
  is_deleted: AnswerUpdateIsDeleted;
  is_flagged: AnswerUpdateIsFlagged;
  is_selected: AnswerUpdateIsSelected;
  is_official: AnswerUpdateIsOfficial;
  is_original_poster: AnswerUpdateIsOriginalPoster;
}
