/**
 * Generated by orval v7.10.0 🍺
 * Do not edit manually.
 * Meetball API
 * API for Meetball - The Summeet's event networking platform
 * OpenAPI spec version: 0.1.0
 */
import type { EventCreateDescription } from './eventCreateDescription';
import type { EventCreateLocation } from './eventCreateLocation';
import type { EventCreateGoogleMapsUrl } from './eventCreateGoogleMapsUrl';
import type { EventCreateParentEventId } from './eventCreateParentEventId';

export interface EventCreate {
  name: string;
  description: EventCreateDescription;
  location: EventCreateLocation;
  google_maps_url: EventCreateGoogleMapsUrl;
  start_date: string;
  end_date: string;
  parent_event_id: EventCreateParentEventId;
  creator_id: string;
}
