/**
 * Generated by orval v7.10.0 🍺
 * Do not edit manually.
 * Meetball API
 * API for Meetball - The Summeet's event networking platform
 * OpenAPI spec version: 0.1.0
 */
import type { EventUpdateDescription } from './eventUpdateDescription';
import type { EventUpdateLocation } from './eventUpdateLocation';
import type { EventUpdateGoogleMapsUrl } from './eventUpdateGoogleMapsUrl';
import type { EventUpdateParentEventId } from './eventUpdateParentEventId';

export interface EventUpdate {
  name: string;
  description: EventUpdateDescription;
  location: EventUpdateLocation;
  google_maps_url: EventUpdateGoogleMapsUrl;
  start_date: string;
  end_date: string;
  parent_event_id: EventUpdateParentEventId;
}
