/**
 * Generated by orval v7.10.0 🍺
 * Do not edit manually.
 * Meetball API
 * API for Meetball - The Summeet's event networking platform
 * OpenAPI spec version: 0.1.0
 */
import type { EventReadDescription } from './eventReadDescription';
import type { EventReadLocation } from './eventReadLocation';
import type { EventReadGoogleMapsUrl } from './eventReadGoogleMapsUrl';
import type { EventReadParentEventId } from './eventReadParentEventId';
import type { EventReadCreatedAt } from './eventReadCreatedAt';
import type { EventReadUpdatedAt } from './eventReadUpdatedAt';

export interface EventRead {
  id: string;
  name: string;
  description: EventReadDescription;
  location: EventReadLocation;
  google_maps_url: EventReadGoogleMapsUrl;
  start_date: string;
  end_date: string;
  parent_event_id: EventReadParentEventId;
  creator_id: string;
  created_at: EventReadCreatedAt;
  updated_at: EventReadUpdatedAt;
}
