/**
 * Generated by orval v7.10.0 🍺
 * Do not edit manually.
 * Meetball API
 * API for Meetball - The Summeet's event networking platform
 * OpenAPI spec version: 0.1.0
 */
import type { EventUpdateDescription } from './eventUpdateDescription';
import type { EventUpdateLocation } from './eventUpdateLocation';
import type { EventUpdateParentEventId } from './eventUpdateParentEventId';

export interface EventUpdate {
  name: string;
  description: EventUpdateDescription;
  location: EventUpdateLocation;
  start_date: string;
  end_date: string;
  parent_event_id: EventUpdateParentEventId;
  image_url?: string | null;
  is_active?: boolean;
  is_cancelled?: boolean;
  is_postponed?: boolean;
}
