/**
 * Generated by orval v7.10.0 🍺
 * Do not edit manually.
 * Meetball API
 * API for Meetball - The Summeet's event networking platform
 * OpenAPI spec version: 0.1.0
 */

export type InteractionType = typeof InteractionType[keyof typeof InteractionType];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const InteractionType = {
  uplift: 'uplift',
  mee_too: 'mee_too',
  i_can_help: 'i_can_help',
  bookmark: 'bookmark',
  view: 'view',
} as const;
