/**
 * Generated by orval v7.10.0 🍺
 * Do not edit manually.
 * Meetball API
 * API for Meetball - The Summeet's event networking platform
 * OpenAPI spec version: 0.1.0
 */
import type { InteractionTarget } from './interactionTarget';
import type { InteractionType } from './interactionType';

export interface InteractionCreate {
  user_id: string;
  target_type: InteractionTarget;
  target_id: string;
  interaction_type: InteractionType;
}
