/**
 * Generated by orval v7.10.0 🍺
 * Do not edit manually.
 * Meetball API
 * API for Meetball - The Summeet's event networking platform
 * OpenAPI spec version: 0.1.0
 */

export type ParticipantRole = typeof ParticipantRole[keyof typeof ParticipantRole];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const ParticipantRole = {
  attendee: 'attendee',
  speaker: 'speaker',
  organizer: 'organizer',
} as const;
