/**
 * Generated by orval v7.10.0 🍺
 * Do not edit manually.
 * Meetball API
 * API for Meetball - The Summeet's event networking platform
 * OpenAPI spec version: 0.1.0
 */
import type { QuestionCreateIsOfficial } from './questionCreateIsOfficial';
import type { QuestionCreateIsAnonymous } from './questionCreateIsAnonymous';
import type { QuestionCreateIsFeatured } from './questionCreateIsFeatured';

export interface QuestionCreate {
  event_id: string;
  user_id: string;
  title: string;
  content: string;
  is_official: QuestionCreateIsOfficial;
  is_anonymous: QuestionCreateIsAnonymous;
  is_featured: QuestionCreateIsFeatured;
}
