/**
 * Generated by orval v7.10.0 🍺
 * Do not edit manually.
 * Meetball API
 * API for Meetball - The Summeet's event networking platform
 * OpenAPI spec version: 0.1.0
 */

export type ReadUsersApiV1UsersGetParams = {
skip?: number;
limit?: number;
};
