/**
 * Generated by orval v7.10.0 🍺
 * Do not edit manually.
 * Meetball API
 * API for Meetball - The Summeet's event networking platform
 * OpenAPI spec version: 0.1.0
 */
import type { UserUpdateLinkedinUrl } from './userUpdateLinkedinUrl';
import type { UserUpdateProfilePicture } from './userUpdateProfilePicture';
import type { UserUpdateBio } from './userUpdateBio';
import type { UserUpdateTitle } from './userUpdateTitle';
import type { UserUpdateIsActive } from './userUpdateIsActive';
import type { UserUpdateLastActiveAt } from './userUpdateLastActiveAt';

export interface UserUpdate {
  linkedin_url: UserUpdateLinkedinUrl;
  first_name: string;
  last_name: string;
  profile_picture: UserUpdateProfilePicture;
  bio: UserUpdateBio;
  title: UserUpdateTitle;
  is_active: UserUpdateIsActive;
  last_active_at: UserUpdateLastActiveAt;
}
