/**
 * Generated by orval v7.10.0 🍺
 * Do not edit manually.
 * Meetball API
 * API for Meetball - The Summeet's event networking platform
 * OpenAPI spec version: 0.1.0
 */
import type { UserReadLinkedinUrl } from './userReadLinkedinUrl';
import type { UserReadProfilePicture } from './userReadProfilePicture';
import type { UserReadBio } from './userReadBio';
import type { UserReadTitle } from './userReadTitle';
import type { UserReadIsActive } from './userReadIsActive';
import type { UserReadCreatedAt } from './userReadCreatedAt';
import type { UserReadUpdatedAt } from './userReadUpdatedAt';
import type { UserReadLastActiveAt } from './userReadLastActiveAt';

export interface UserRead {
  id: string;
  linkedin_url: UserReadLinkedinUrl;
  auth_id: string;
  email: string;
  first_name: string;
  last_name: string;
  profile_picture: UserReadProfilePicture;
  bio: UserReadBio;
  title: UserReadTitle;
  is_active: UserReadIsActive;
  created_at: UserReadCreatedAt;
  updated_at: UserReadUpdatedAt;
  last_active_at: UserReadLastActiveAt;
}
