/**
 * Generated by orval v7.10.0 🍺
 * Do not edit manually.
 * Meetball API
 * API for Meetball - The Summeet's event networking platform
 * OpenAPI spec version: 0.1.0
 */
import type { UserCreateLinkedinUrl } from './userCreateLinkedinUrl';
import type { UserCreateProfilePicture } from './userCreateProfilePicture';
import type { UserCreateBio } from './userCreateBio';
import type { UserCreateTitle } from './userCreateTitle';
import type { UserCreateIsActive } from './userCreateIsActive';

export interface UserCreate {
  linkedin_url: UserCreateLinkedinUrl;
  auth_id: string;
  email: string;
  first_name: string;
  last_name: string;
  full_name: string;
  profile_picture: UserCreateProfilePicture;
  bio: UserCreateBio;
  title: UserCreateTitle;
  is_active: UserCreateIsActive;
}
